# Generated by Django 4.2 on 2023-05-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_fitnessdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessdata',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='fitnessdata',
            name='question_2',
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='goal',
            field=models.CharField(default='Lose weight', max_length=200),
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='height',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='weight',
            field=models.FloatField(default=145),
        ),
        migrations.AddField(
            model_name='fitnessdata',
            name='workout_routine',
            field=models.TextField(blank=True),
        ),
    ]
