# Generated by Django 4.2 on 2023-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_fitnessdata_question_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
