# Generated by Django 4.2 on 2023-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_fitnessdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdata',
            name='fitness_level',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
